import NavBar from '@/components/organism/navbar';
import type { Metadata } from 'next';
import { Inter, Poppins, Roboto_Slab, Rufina } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

const robotoSlab = Roboto_Slab({
  weight: ['500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-slab',
});

const poppins = Poppins({
  weight: ['500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
});

const rufina = Rufina({
  weight: ['400', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rufina',
});

export const metadata: Metadata = {
  title: 'Hello Molly',
  description: 'Generated by create next app',
};

const bodyStyles = `${inter.className} ${robotoSlab.variable} ${poppins.variable} ${rufina.variable}  min-h-screen bg-white`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={bodyStyles}>
        <NavBar />
        <div className='min-w-screen-lg mx-auto'>{children}</div>
      </body>
    </html>
  );
}
